version: '3'
services:
    ui:
        container_name: ui
        restart: always 
        build: ./ui
        ports:
            - "3000:3000"
        volumes:
            - ./ui:/app
        links:
            - happybnb
    happybnb:
        container_name: happybnb
        restart: always
        volumes:
            - ./server:/app
        build: ./server
        ports:
            - '3001:8080'
        links:
            - mongo
    mongo:
        image: mongo
        volumes:
            - ./data:/data/db
        ports:
            - '27016:27017'
        environment:
            - MONGODB_INITDB_ROOT_USERNAME=hackatown2019
            - MONGODB_INITDB_ROOT_PASSWORD=password
