version: '3'
services:
    happybnb:
        container_name: happybnb
        restart: always
        volumes:
            - ./server:/app
        build: ./server
        ports:
            - '80:8080'
        links:
            - mongo
    mongo:
        image: mongo
        volumes:
            - ./data:/data/db
        ports:
            - '27016:27017'
