version: '3'
services:
    happybnb:
        container_name: happybnb
        restart: always
        build: ./server
        ports:
            - '3000:8080'
        links:
            - mongo
    mongo:
        image: mongo
        volumes:
            - ./data:/data/db
        ports:
            - '27017:27017'
